"use client";

import { ReactNode } from 'react';
import GlobalStyle from '../styles/global';
<<<<<<< HEAD
import { AccountProvider } from '../components/AccountContext';
=======
>>>>>>> 69b69744a3735a5c8611f4acd05bbe41a1becef4

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <title>Can</title>
        <meta name="description" content="Generated by Next.js" />
      </head>
      <body suppressHydrationWarning={true}>
        <AccountProvider>
          <GlobalStyle />
          {children}
        </AccountProvider>
      </body>
    </html>
  );
};

export default Layout;
