import { ReactNode } from 'react';
import GlobalStyle from '../styles/global';

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <title>Can</title>
        <meta name="description" content="Generated by Next.js" />
      </head>
      <body suppressHydrationWarning={true}>
        <GlobalStyle />
        {children}
      </body>
    </html>
  );
};

export default Layout;